In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# from sklearn.svm import OneClassSVM
# from sklearn.preprocessing import StandardScaler
# from sklearn.metrics import classification_report
%matplotlib inline
sns.set_style('darkgrid')

In [2]:
df1 = pd.read_csv("Algerian_forest_fires_dataset.csv")
df2 = pd.read_csv("forestfires.csv")

In [3]:
df1

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classess
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
242,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
243,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
244,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
245,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [4]:
df1=df1[['Temperature','RH','Rain','month','Ws','Classess']]

In [5]:
df2

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [6]:
month_mapping = {
    'jan':1,'feb':2,'mar':3,'apr':4,
   'may':5,'jun':6,'jul':7,'aug':8,
    'sep':9,'oct':10,'nov':11,'dec':12
}
df2['month'] = df2['month'].map(month_mapping)

In [7]:
df2=df2[['temp','RH','rain','month','wind']]

In [8]:
df2=df2.rename(columns={'temp':'Temperature','wind':'Ws','rain':'Rain'})

In [9]:
df1

    Temperature  RH  Rain month  Ws  Classess
0            29  57     0     6  18  not fire
1            29  61   1.3     6  13  not fire
2            26  82  13.1     6  22  not fire
3            25  89   2.5     6  13  not fire
4            27  77     0     6  16  not fire
..          ...  ..   ...   ...  ..       ...
241          30  65     0     9  14      fire
242          28  87   4.4     9  15  not fire
243          27  87   0.5     9  29  not fire
244          24  54   0.1     9  18  not fire
245          24  64   0.2     9  15  not fire

[246 rows x 6 columns]

In [10]:
df2['Classess']='fire'

In [11]:
df = pd.concat([df1, df2], ignore_index=True)

In [12]:
df

    Temperature  RH  Rain month   Ws  Classess
0            29  57     0     6   18  not fire
1            29  61   1.3     6   13  not fire
2            26  82  13.1     6   22  not fire
3            25  89   2.5     6   13  not fire
4            27  77     0     6   16  not fire
..          ...  ..   ...   ...  ...       ...
758        27.8  32   0.0     8  2.7      fire
759        21.9  71   0.0     8  5.8      fire
760        21.2  70   0.0     8  6.7      fire
761        25.6  42   0.0     8  4.0      fire
762        11.8  31   0.0    11  4.5      fire

[763 rows x 6 columns]

In [13]:
df.describe()

       Temperature   RH   Rain  month     Ws Classess
count          761  761  761.0    761  761.0      761
unique         212  138   47.0     17   40.0        3
top             35   27    0.0      8    2.2     fire
freq            29   33  509.0    184   53.0      654

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 763 entries, 0 to 762
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  761 non-null    object
 1   RH           761 non-null    object
 2   Rain         761 non-null    object
 3   month        761 non-null    object
 4   Ws           761 non-null    object
 5   Classess     761 non-null    object
dtypes: object(6)
memory usage: 35.9+ KB

In [15]:
df['month'].value_counts()

month
8        184
9        172
8         62
7         61
6         60
9         60
3         54
7         32
2         20
6         17
10        15
4          9
12         9
1          2
5          2
month      1
11         1
Name: count, dtype: int64

In [16]:
df=df[df['month']!= 'month']

In [17]:
df['month'] = pd.to_numeric(df['month'], errors='coerce')

C:\Users\akarsh\AppData\Local\Temp\ipykernel_10960\3836178953.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = pd.to_numeric(df['month'], errors='coerce')

In [18]:
df['month'].value_counts()

month
8.0     246
9.0     232
7.0      93
6.0      77
3.0      54
2.0      20
10.0     15
4.0       9
12.0      9
1.0       2
5.0       2
11.0      1
Name: count, dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 762 entries, 0 to 762
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  760 non-null    object
 1   RH           760 non-null    object
 2   Rain         760 non-null    object
 3   month        760 non-null    float64
 4   Ws           760 non-null    object
 5   Classess     760 non-null    object
dtypes: float64(1), object(5)
memory usage: 41.7+ KB

In [20]:
df.dropna()

    Temperature  RH  Rain  month   Ws  Classess
0            29  57     0    6.0   18  not fire
1            29  61   1.3    6.0   13  not fire
2            26  82  13.1    6.0   22  not fire
3            25  89   2.5    6.0   13  not fire
4            27  77     0    6.0   16  not fire
..          ...  ..   ...    ...  ...       ...
758        27.8  32   0.0    8.0  2.7      fire
759        21.9  71   0.0    8.0  5.8      fire
760        21.2  70   0.0    8.0  6.7      fire
761        25.6  42   0.0    8.0  4.0      fire
762        11.8  31   0.0   11.0  4.5      fire

[760 rows x 6 columns]

In [21]:
df3=pd.read_csv('not_fire.csv')

In [22]:
df3

     Temperature  RH  Rain  month  Ws  label
0              5  88    15      1   3      0
1              6  85    12      1   4      0
2              7  82    10      1   5      0
3              8  80     9      1   6      0
4              9  78     8      2   5      0
..           ...  ..   ...    ...  ..    ...
101           13  88    15     11   3      0
102           12  90    16     11   2      0
103           11  92    17     11   3      0
104           10  90    15     12   4      0
105            8  88    14     12   3      0

[106 rows x 6 columns]

In [23]:
df3=df3.rename(columns={'label':'Classess'})

In [24]:
df3.sample()

    Temperature  RH  Rain  month  Ws  Classess
38           14  82    12      8   4         0

In [25]:
df3['Classess']='not fire'

In [26]:
df3.sample()

    Temperature  RH  Rain  month  Ws  Classess
80           11  80    12      3   4  not fire

In [27]:
df = pd.concat([df, df3], ignore_index=True)

In [28]:
df['Classess'].value_counts()

Classess
fire        654
not fire    212
Name: count, dtype: int64

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 868 entries, 0 to 867
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  866 non-null    object
 1   RH           866 non-null    object
 2   Rain         866 non-null    object
 3   month        866 non-null    float64
 4   Ws           866 non-null    object
 5   Classess     866 non-null    object
dtypes: float64(1), object(5)
memory usage: 40.8+ KB

In [30]:
from sklearn.preprocessing import OneHotEncoder

In [31]:
df=pd.get_dummies(df,columns=['Classess'])

In [32]:
df=df.drop('Classess_not fire', axis=1)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 868 entries, 0 to 867
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Temperature    866 non-null    object
 1   RH             866 non-null    object
 2   Rain           866 non-null    object
 3   month          866 non-null    float64
 4   Ws             866 non-null    object
 5   Classess_fire  868 non-null    bool
dtypes: bool(1), float64(1), object(4)
memory usage: 34.9+ KB

In [34]:
class_mapping = {
    True:1,False:0
}
df['Classess_fire'] = df['Classess_fire'].map(class_mapping)

In [35]:
df.sample(2)

    Temperature  RH Rain  month  Ws  Classess_fire
83           36  53    0    8.0  16              1
235          35  34    0    9.0  17              1

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X=df.drop('Classess_fire', axis=1)
y=df['Classess_fire']

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    stratify=y,
    random_state=42
)

In [39]:
X_train.sample(4)

    Temperature  RH Rain  month   Ws
766           9  78    8    2.0    5
865          11  92   17   11.0    3
15           29  89  0.7    6.0   13
356        18.8  18  0.0    3.0  4.5

In [40]:
X_test.sample(4)

    Temperature  RH Rain  month   Ws
221          31  62    0    9.0   15
154          28  58  2.2    7.0   18
735        28.7  33  0.0    8.0  4.0
711        10.2  45  0.0    3.0  5.8

In [41]:
y_train.sample(4)

550    1
79     1
171    1
57     1
Name: Classess_fire, dtype: int64

In [42]:
y_test.sample(4)

294    1
482    1
178    0
611    1
Name: Classess_fire, dtype: int64

In [43]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier

In [44]:
pipeline = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("model", XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        scale_pos_weight=6,      # for 1:6 imbalance
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    ))
])

In [45]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=0.8, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric='logloss',
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, random_state=42, ...))])

In [51]:
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.metrics import confusion_matrix
print("Confusion Matrix (threshold = 0.5)")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("ROC-AUC:", roc_auc_score(y_test, y_prob))

Confusion Matrix (threshold = 0.5)
[[ 55   9]
 [  3 194]]

Classification Report
              precision    recall  f1-score   support

           0       0.95      0.86      0.90        64
           1       0.96      0.98      0.97       197

    accuracy                           0.95       261
   macro avg       0.95      0.92      0.94       261
weighted avg       0.95      0.95      0.95       261

ROC-AUC: 0.9880631345177665

In [53]:
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.metrics import confusion_matrix


y_pred = pipeline.predict(X_test)
y_prob = pipeline.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

              precision    recall  f1-score   support

           0       0.95      0.86      0.90        64
           1       0.96      0.98      0.97       197

    accuracy                           0.95       261
   macro avg       0.95      0.92      0.94       261
weighted avg       0.95      0.95      0.95       261

ROC-AUC: 0.9880631345177665

In [55]:
thresholds = [0.2, 0.3, 0.4, 0.45, 0.5]

for t in thresholds:
    y_pred_t = (y_prob >= t).astype(int)
    print(f"\nThreshold = {t}")
    print(confusion_matrix(y_test, y_pred_t))
    print(classification_report(y_test, y_pred_t))

Threshold = 0.2
[[ 48  16]
 [  1 196]]
              precision    recall  f1-score   support

           0       0.98      0.75      0.85        64
           1       0.92      0.99      0.96       197

    accuracy                           0.93       261
   macro avg       0.95      0.87      0.90       261
weighted avg       0.94      0.93      0.93       261


Threshold = 0.3
[[ 51  13]
 [  2 195]]
              precision    recall  f1-score   support

           0       0.96      0.80      0.87        64
           1       0.94      0.99      0.96       197

    accuracy                           0.94       261
   macro avg       0.95      0.89      0.92       261
weighted avg       0.94      0.94      0.94       261


Threshold = 0.4
[[ 53  11]
 [  3 194]]
              precision    recall  f1-score   support

           0       0.95      0.83      0.88        64
           1       0.95      0.98      0.97       197

    accuracy                           0.95       261
   macro avg       0.95      0.91      0.92       261
weighted avg       0.95      0.95      0.95       261


Threshold = 0.45
[[ 53  11]
 [  3 194]]
              precision    recall  f1-score   support

           0       0.95      0.83      0.88        64
           1       0.95      0.98      0.97       197

    accuracy                           0.95       261
   macro avg       0.95      0.91      0.92       261
weighted avg       0.95      0.95      0.95       261


Threshold = 0.5
[[ 55   9]
 [  3 194]]
              precision    recall  f1-score   support

           0       0.95      0.86      0.90        64
           1       0.96      0.98      0.97       197

    accuracy                           0.95       261
   macro avg       0.95      0.92      0.94       261
weighted avg       0.95      0.95      0.95       261

In [57]:
best_threshold = 0.4   # choose based on F1 / recall

y_final = (y_prob >= best_threshold).astype(int)

print("\nFINAL MODEL (threshold = 0.4)")
print(confusion_matrix(y_test, y_final))
print(classification_report(y_test, y_final))

FINAL MODEL (threshold = 0.4)
[[ 53  11]
 [  3 194]]
              precision    recall  f1-score   support

           0       0.95      0.83      0.88        64
           1       0.95      0.98      0.97       197

    accuracy                           0.95       261
   macro avg       0.95      0.91      0.92       261
weighted avg       0.95      0.95      0.95       261

In [59]:
# import pickle

# with open("xgb_pipeline.pkl", "wb") as f:
#     pickle.dump(pipeline, f)

In [61]:
test_cases = [
    [38, 15, 0, 6, 20],
    [30, 70, 5, 7, 10],
    [5, 80, 10, 12, 5],
    [28, 25, 0, 4, 15],
    [35, 65, 12, 5, 5],
    [33, 20, 0, 10, 30],
    [30, 40, 1, 8, 10],
    [40, 10, 0, 7, 25],
    [25, 50, 0, 9, 5],
    [32, 30, 0, 3, 15],
    [20, 60, 2, 11, 10],
    [37, 12, 0, 8, 20],
    [15, 70, 5, 1, 5],
    [29, 35, 0, 5, 12],
    [26, 55, 3, 2, 8],
    [39, 10, 0, 9, 30],
    [22, 65, 7, 12, 5],
    [34, 25, 0, 6, 18],
    [27, 45, 2, 7, 12],
    [31, 20, 0, 8, 20]
]

In [63]:
df_test = pd.DataFrame(test_cases, columns=["Temperature","RH","Rain","month","Ws"])

In [65]:
predictions = pipeline.predict(df_test)

In [67]:
predictions

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])